---
swagger: "2.0"
info:
  title: Mock Server
  description: ""
  version: 1.0.0
host: localhost:10010
basePath: /
schemes:
- http
paths:
  /user:
    post:
      tags:
      - user
      summary: "\u521B\u5EFA\u7528\u6237"
      description: "\u521B\u5EFA\u65B0\u7528\u6237"
      operationId: createUser
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        description: "\u521B\u5EFA\u7528\u6237"
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        200:
          description: "\u521B\u5EFA\u6210\u529F"
          schema:
            $ref: '#/definitions/ApiResponse'
    x-swagger-router-controller: /user
  /user/{username}:
    get:
      tags:
      - user
      summary: "\u6839\u636E\u7528\u6237\u540D\u83B7\u53D6\u7528\u6237\u4FE1\u606F"
      description: ""
      operationId: getUserByName
      produces:
      - application/xml
      - application/json
      parameters:
      - name: username
        in: path
        description: "\u7528\u6237\u540D"
        required: true
        type: string
      responses:
        200:
          description: "\u83B7\u53D6\u6210\u529F"
          schema:
            $ref: '#/definitions/User'
        400:
          description: "\u65E0\u6548\u7684\u7528\u6237\u540D"
        404:
          description: "\u7528\u6237\u540D\u4E0D\u5B58\u5728"
    x-swagger-router-controller: /user/
definitions:
  User:
    properties:
      id:
        type: integer
        format: int64
        example: "1"
      username:
        type: string
        example: "\u5F20\u4E09"
      firstName:
        type: string
        example: "\u5F20"
      lastName:
        type: string
        example: "\u4E09"
      email:
        type: string
        example: test@shopex.cn
      password:
        type: string
        example: admin123
      phone:
        type: string
        example: "13918087654"
      userStatus:
        description: User Status
        type: integer
        format: int32
        example: "true"
    type: object
    xml:
      name: User
  ApiResponse:
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
    type: object
...
